# Generated by Django 5.2.10 on 2026-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('base_url', models.URLField()),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Go', 'Go'), ('Java', 'Java'), ('C#', 'C#'), ('PHP', 'PHP')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
