# Generated by Django 5.2.10 on 2026-02-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Javascript', 'JavaScript'), ('Go', 'Go'), ('Java', 'Java'), ('C#', 'C#'), ('PHP', 'PHP')], max_length=50),
        ),
    ]
