# Generated by Django 5.2.10 on 2026-02-04 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='base_url',
            field=models.URLField(validators=[django.core.validators.RegexValidator(code='invalid_base_url', message="Base URL must be in 'www.' format (e.g., http://).", regex='^https:\\/\\/www\\..+')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_version', message="Version must be in 'X.X.X' or 'X.X.X.X' format (e.g., 1.0.0).", regex='^(\\d+\\.\\d+\\.\\d+|\\d+\\.\\d+\\.\\d+\\.\\d+)$')]),
        ),
    ]
