# Generated by Django 5.2.10 on 2026-01-21 14:02

import endpoints.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='path',
            field=models.CharField(help_text='Example: /api/v1/users/', max_length=300, validators=[endpoints.validators.validate_start_slash]),
        ),
    ]
